import type { IconType } from "react-icons";
import {
  SiC,
  SiCss,
  SiCplusplus,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiGit,
  SiGithub,
  SiGooglegemini,
  SiGreensock,
  SiHtml5,
  SiHuggingface,
  SiJavascript,
  SiJupyter,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiOpenjdk,
  SiPandas,
  SiPostgresql,
  SiPython,
  SiReact,
  SiScikitlearn,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
} from "react-icons/si";
import {
  Blocks,
  BrainCircuit,
  Code2,
  Eye,
  FileCode2,
  Image,
  Network,
  Palette,
  Sparkles,
  type LucideIcon,
} from "lucide-react";
import type { TechnologyId } from "@/data/skills";

type TechnologyIconType = IconType | LucideIcon;

export const technologyIcons: Record<TechnologyId, TechnologyIconType> = {
  python: SiPython,
  typescript: SiTypescript,
  javascript: SiJavascript,
  java: SiOpenjdk,
  cplusplus: SiCplusplus,
  c: SiC,
  ballerina: Code2,
  react: SiReact,
  nextjs: SiNextdotjs,
  html5: SiHtml5,
  css3: SiCss,
  tailwind: SiTailwindcss,
  gsap: SiGreensock,
  nodejs: SiNodedotjs,
  express: SiExpress,
  fastapi: SiFastapi,
  rest: Network,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  firebase: SiFirebase,
  supabase: SiSupabase,
  pandas: SiPandas,
  numpy: SiNumpy,
  jupyter: SiJupyter,
  scikitlearn: SiScikitlearn,
  huggingface: SiHuggingface,
  openai: Sparkles,
  gemini: SiGooglegemini,
  "machine-learning": BrainCircuit,
  "deep-learning": Network,
  "computer-vision": Eye,
  rag: Blocks,
  git: SiGit,
  github: SiGithub,
  docker: SiDocker,
  linux: SiLinux,
  vscode: FileCode2,
  vercel: SiVercel,
  figma: SiFigma,
  photoshop: Image,
  illustrator: Palette,
  canva: Palette,
};

export function TechnologyIcon({ id }: { id: string }) {
  const Icon = technologyIcons[id as TechnologyId];
  if (!Icon) return null;
  return <Icon aria-hidden="true" />;
}
